### ISSUE TITLE
Migration on initial load for Transaction_User FK constraint fails

### ISSUE THREAD

**Issue by charlieknoll** [kazimanzurrashid/my-walletz-backbone#1]
I cloned the repo and built succesfully, on first run I receive error:

Introducing FOREIGN KEY constraint 'Transaction_User' on table 'Transactions' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint. See previous errors.

I tried commenting out the Foreign Key lines in the TransactionMigration.cs but same error occurs:

```
        CreateTable(
            "dbo.Transactions",
            c =>
            new
                {
                    Id = c.Int(nullable: false, identity: true),
                    Payee = c.String(nullable: true, maxLength: 128),
                    Notes = c.String(maxLength: 512),
                    AccountId = c.Int(nullable: false),
                    CategoryId = c.Int(),
                    UserId = c.Int(nullable: false),
                    Amount = c.Decimal(nullable: false, precision: 18, scale: 2),
                    PostedAt = c.DateTime(nullable: false),
                })
            .PrimaryKey(t => t.Id);
            //.ForeignKey("dbo.Accounts", t => t.AccountId)
            //.ForeignKey("dbo.Categories", t => t.CategoryId);
            //.ForeignKey("dbo.Users", t => t.UserId);
```

**Comment by kazimanzurrashid** [comment]
Interesting, i was not able to reproduce it, what happens if you explicitly set false as cascadeOnDelete on the foreign key statement?

**Comment by charlieknoll** [comment]
I get the same error setting cascadeOnDelete = false.  I think there may be some build artifacts that are not getting overwritten.  I deleted the 201305151509256_TransactionMigration.cs files and the same error occurs.  I'm running Visual Studio Pro.  Is there supposed to be a designer available for the migrations?

**Comment by kazimanzurrashid** [comment]
I have regenerated the migration files, do let me know if the issue still exists.

**Comment by bzamora** [comment]
I have the same error even after updating with most recent changes. The only change I made was pointing to Sql2012 instead of LocalDb in web.config (added stack trace, notice error comes from RegisterMembership)

{"Introducing FOREIGN KEY constraint 'Transaction_User' on table 'Transactions' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.\r\nCould not create constraint. See previous errors."}
    [System.Data.SqlClient.SqlException]: {"Introducing FOREIGN KEY constraint 'Transaction_User' on table 'Transactions' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.\r\nCould not create constraint. See previous errors."}
    Data: {System.Collections.ListDictionaryInternal}
    HelpLink: null
    HResult: -2146232060
    InnerException: null
    Message: "Introducing FOREIGN KEY constraint 'Transaction_User' on table 'Transactions' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.\r\nCould not create constraint. See previous errors."
    Source: ".Net SqlClient Data Provider"
StackTrace: "   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout)\r\n   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at System.Data.SqlClient.
SqlProviderServices.<>c__DisplayClassa.<DbCreateDatabase>b__8(SqlConnection conn)\r\n   at System.Data.SqlClient.SqlProviderServices.UsingConnection(SqlConnection sqlConnection, Action`1 act)\r\n   at System.Data.SqlClient.SqlProviderServices.DbCreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)\r\n   at System.Data.Objects.ObjectContext.CreateDatabase()\r\n   at MyWalletz.Infrastructure.StarterKitConfig.RegisterMembership() in c:\\Projects\\GitHub\\my-walletz-backbone\\source\\MyWalletz\\App_Start\\StarterKitConfig.cs:line 114"
    TargetSite: {Void OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1[System.Action])}

**Comment by charlieknoll** [comment]
I downloaded the latest and still get the same error.  After doing further research, I don't think that the migrations are being used at all and it is spinning up the database using the POCO entities.   I deleted the transactions property on the User entity and the User property on the transactions entity and db was created successfully.  Note that I did not remove the User Foreign Key from the migrations.

I then reverted the repo and  I changed the UserId property on the Transactions entity to nullable and was able to spin up the db successfully:

public int? UserId { get; set; }
